# Generated by Django 2.1 on 2019-01-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaporama_image', models.ImageField(upload_to='images/')),
                ('diaporama_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', models.ImageField(upload_to='images/')),
                ('post_titre', models.CharField(max_length=300)),
                ('date_de_publication', models.DateTimeField(auto_now_add=True)),
                ('post_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(max_length=300)),
                ('service_description', models.TextField()),
                ('service_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
